---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - entropyk.io
  resources:
  - chaosexperiments
  - chaosschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - entropyk.io
  resources:
  - chaosexperiments/finalizers
  - chaosschedules/finalizers
  verbs:
  - update
- apiGroups:
  - entropyk.io
  resources:
  - chaosexperiments/status
  - chaosschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
